### PR TITLE
Added support for DNS over TCP

### PR DESCRIPTION
**Pull request by takeshixx**
Added the `--tcp` argument to query DNS over TCP instead of UDP. Useful in scenarios where queries need traverse HTTP/SOCKS5 proxies.

### CODE REVIEW

**Comment by mschwager** [comment]
Nice! If you could fix up the tests this LGTM :+1:

**Comment by takeshixx** [comment]
I've added the TCP flag to the mock calls, test look good now.

**Comment by mschwager** [comment]
Great thanks!

**Comment by mschwager** [comment]
Heads up, I just released a new version. So you should be able to upgrade via pip and use the new flag :)

**Pull request merged**
